#include "p16f887.inc"

; CONFIG1
; __config 0xE895
 __CONFIG _CONFIG1, _FOSC_INTRC_CLKOUT & _WDTE_OFF & _PWRTE_OFF & _MCLRE_OFF & _CP_ON & _CPD_OFF & _BOREN_OFF & _IESO_OFF & _FCMEN_ON & _LVP_OFF
; CONFIG2
; __config 0xFFFF
 __CONFIG _CONFIG2, _BOR4V_BOR40V & _WRT_OFF


GPR_VAR    UDATA
    
    COUNTER RES 1		;TMR0 REPEAT COUNTER
    ONESECTIMER   RES	1	;COUNTS TO 1 SEC
    PHASETIMER	RES 1		;COUNTS TOWARDS SPECIFIC TIMES
    CONTROL RES	1		;MODE BIT CONTROL
				;BIT 0 DAY MODE
				;BIT 1 AFTERNOON MODE
				;BIT 2 NIGHT MODE
				;BIT 3 MANUAL MODE
    SECTIMER	RES 1
    CHANGEVAR	RES 1
	TM  RES	1
	TIMERTWOFIVE	RES 1
	D2  RES	1
	D1  RES	1


RES_VECT  CODE    0x0000        ; processor reset vector
    GOTO    SETUP   
 
    
ISR_VECT CODE 0X0004
 BCF INTCON, GIE		;CLEARED TO DISBLE FURTHER INTERRUPTS
 
 
 BTFSC PORTB, RB0		;CHECK STATE OF RB0 (DAY)
 GOTO DY
 BTFSC PORTB, RB1		;CHECK STATE OF RB1 (AFTERNOON)
 GOTO AN
 BTFSC PORTB, RB2		;CHECK STATE OF RB2 (NIGHT)
 GOTO NG
 BTFSC PORTB, RB3		;CHECK STATE OF RB3 (MANUAL)
 GOTO MAN
 BTFSC PORTB, RB4		;CHECK STATE OF RB4 (RESET)
 GOTO RESETLBL
 GOTO EXIT
 
 
 DY:
    CLRF CHANGEVAR
    CLRF CONTROL
    BSF CONTROL, 0
    BSF CHANGEVAR, 0
    GOTO EXIT
    
AN:
    CLRF CHANGEVAR
    CLRF CONTROL
    BSF CONTROL, 1
    BSF CHANGEVAR, 1
    GOTO EXIT
    
NG:
    CLRF CHANGEVAR
    CLRF CONTROL
    BSF CONTROL, 2
    BSF CHANGEVAR, 2
    GOTO EXIT
    
MAN:
    CLRF CHANGEVAR
    CLRF CONTROL
    BSF CONTROL, 3
    BSF CHANGEVAR, 3 
    GOTO EXIT
    
 
 
 RESETLBL:
    CLRF PHASETIMER
    CLRF TIMERTWOFIVE
    CLRF TM
    CLRF SECTIMER
    CLRF PORTC
    CLRF PORTD
    GOTO EXIT
 
 EXIT:
 CALL DELAY
 BCF INTCON, RBIF		;CLEAR INTERRUPT FLAG ON PORT B
 BSF INTCON, GIE		;ENABLE FURTHER INTERRUPTS
RETFIE				;RETURN FROM INTERRUPT
 
 
			
 



MAIN_PROG CODE			; let linker place main program

     
SETUP
 BCF STATUS, RP1		;
 BSF STATUS, RP0		;BANK 1
 BSF IOCB, IOCB0		;INTERRUPT ON CHANGE ENABLED RB0
 BSF IOCB, IOCB1		;INTERRUPT ON CHANGE ENABLED RB1
 BSF IOCB, IOCB2		;INTERRUPT ON CHANGE ENABLED RB2
 BSF IOCB, IOCB3		;INTERRUPT ON CHANGE ENABLED RB3
 BSF IOCB, IOCB4		;INTERRUPT ON CHANGE ENABLED RB4
 BSF OSCCON, IRCF2		;
 BSF OSCCON, IRCF1		;
 BSF OSCCON, IRCF0		;OSC FREC 8MHz
 BSF STATUS, RP0		;
 BSF STATUS, RP1		;BANK 3
 CLRF ANSEL			;DIGITAL OUTPUT
 CLRF ANSELH			;DIGITAL OUTPUT
 BCF STATUS, RP1		;BANK 1
 CLRF TRISD			;PORTD OUTPUT
				;RD0 GREEN LED SL1
				;RD1 YELLOW LED SL1
				;RD2 RED LED SL1
				;RD3 GREEN LED SL2
				;RD4 YELLOW LED SL2
				;RD5 RED LED SL2
				;RD6 GREEN LED SL3
				;RD7 YELLOW LED SL3
 CLRF TRISC			;PORTC OUTPUT
				;RC0 RED LED SL3
				;RC1 YELLOW SL4
				
 BSF TRISB, 0			;RB0 INPUT	(PB)	    DAY 
 BSF TRISB, 1			;RB1 INPUT	(PB)	    AFTERNOON 
 BSF TRISB, 2			;RB2 INPUT	(PB)	    NIGHT 
 BSF TRISB, 3			;RB3 INPUT	(PB)	    MANUAL 
 BSF TRISB, 4
 CALL INITTMR0			;CALL SUBR TO INITIALIZE TMR0	    
 CLRF PORTD			;SET VALUE TO 0
 CLRF PORTB			;SET VALUE TO 0
 CLRF PORTC			;SET VALUE TO 0
 BCF STATUS, RP0		;
 BCF STATUS, RP1		;BANK 0
 BSF INTCON, GIE		;ENABLE GLOBAL INTERRUPT
 BSF INTCON, RBIE		;ENABLE INTERRUPTS ON PORTB (ON CHANGE)
 BSF INTCON, RBIF		;ENABLE INTERRUPT ON PORTB FLAG
 CLRF CONTROL
 CLRF PHASETIMER
 CLRF CHANGEVAR
 BSF CHANGEVAR, 3			;START MODE
 
 MOVLW .1
 MOVWF PHASETIMER

 
 
 
 
MAINLOOP:
    CLRF TIMERTWOFIVE
    CLRF CONTROL
    CLRF PHASETIMER
    CLRF SECTIMER
    CLRF TM
    
    
    MOVF CHANGEVAR, W
    MOVWF CONTROL
    
    MOVLW .1
    MOVWF TIMERTWOFIVE
    
    GOTO CHECKT0IF
    
    
    
CHECKT0IF:
    BTFSS INTCON, T0IF		;CHECK INTERRUPTION FLAG T0 STATUS
    GOTO CHECKT0IF 		;RETURN TO CHECKT0IF
    BCF INTCON, T0IF		;CLEAR INTERRUPTION FLAG
    MOVLW .61			;MOVE LITERAL 61 TO W
    MOVWF TMR0			;MOVE W TO TMR0
    INCF COUNTER, F		;INCREASE COUNTER
    MOVF COUNTER, W		;MOVE COUNTER VAR TO W
    SUBLW .10			;SUBSTRACT 10 TO W (25 mSEC)
    BTFSS STATUS, Z		;CHECH ZERO FLAG STATUS
    GOTO CHECKT0IF
    CLRF COUNTER		;CLEAR COUNTER VAR
    INCF TM
    MOVF TM, W
    SUBLW .20
    BTFSS STATUS, Z
    GOTO SEC
    CLRF TM
    INCF TIMERTWOFIVE
    SEC:
    INCF SECTIMER, F
    MOVF SECTIMER, W
    SUBLW .8
    BTFSS STATUS, Z
    GOTO CHECKT0IF
    CLRF SECTIMER
    GOTO TIMECHECK
    

    
    TIMECHECK:
    INCF PHASETIMER
    
    
    TIMECHECK0:
    MOVF PHASETIMER, W
    SUBLW .1	    ;1SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK2
    GOTO PHASE1
    

    TIMECHECK2:
    MOVF PHASETIMER, W
    SUBLW .17		    ;17SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK3
    GOTO PHASE2
    
    TIMECHECK3:
    MOVF PHASETIMER, W
    SUBLW .20		    ;20SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK4
    GOTO PHASE3
    
    TIMECHECK4:
    MOVF PHASETIMER, W
    SUBLW .30		    ;30SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK5
    GOTO PHASE4
    
    TIMECHECK5:
    MOVF PHASETIMER, W
    SUBLW .33		    ;33SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK6
    GOTO PHASE5
    
    TIMECHECK6:
    MOVF PHASETIMER, W
    SUBLW .37		    ;37SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK7
    GOTO PHASE6
    
    TIMECHECK7:
    MOVF PHASETIMER, W
    SUBLW .40		    ;40SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK8
    GOTO PHASE7
    
    TIMECHECK8:
    MOVF PHASETIMER, W
    SUBLW .50		    ;50SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK9
    GOTO PHASE8
    
    TIMECHECK9:
    MOVF PHASETIMER, W
    SUBLW .53		    ;53SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK10
    GOTO PHASE9
    
    TIMECHECK10:
    MOVF PHASETIMER, W
    SUBLW .57		    ;57SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK11
    GOTO PHASE10
    
    TIMECHECK11:
    MOVF PHASETIMER, W
    SUBLW .60
    BTFSS STATUS, Z
    GOTO TIMECHECK21
    GOTO PHASE11
    
    TIMECHECK21:
    MOVF TIMERTWOFIVE, W
    SUBLW .1		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK22
    GOTO PHASEON
    
    TIMECHECK22:
    MOVF TIMERTWOFIVE, W
    SUBLW .2		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK23
    GOTO PHASEOFF
    
    TIMECHECK23:
    MOVF TIMERTWOFIVE, W
    SUBLW .3		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK24
    GOTO PHASEON
    
    TIMECHECK24:
    MOVF TIMERTWOFIVE, W
    SUBLW .4		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK25
    GOTO PHASEOFF
    
    TIMECHECK25:
    MOVF TIMERTWOFIVE, W
    SUBLW .5		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK26
    GOTO PHASEON
    
    TIMECHECK26:
    MOVF TIMERTWOFIVE, W
    SUBLW .6		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK27
    GOTO PHASEOFF
    
    TIMECHECK27:
    MOVF TIMERTWOFIVE, W
    SUBLW .7		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK28
    GOTO PHASEON
    
    TIMECHECK28:
    MOVF TIMERTWOFIVE, W
    SUBLW .8		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK29
    GOTO PHASEOFF
    
    TIMECHECK29:
    MOVF TIMERTWOFIVE, W
    SUBLW .9		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK30
    GOTO PHASEON
    
    TIMECHECK30:
    MOVF TIMERTWOFIVE, W
    SUBLW .10	    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK31
    GOTO PHASEOFF
    
    TIMECHECK31:
    MOVF TIMERTWOFIVE, W
    SUBLW .11		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK32
    GOTO PHASEON
    
    TIMECHECK32:
    MOVF TIMERTWOFIVE, W
    SUBLW .12		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK33
    GOTO PHASEOFF
    
    TIMECHECK33:
    MOVF TIMERTWOFIVE, W
    SUBLW .13		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK34
    GOTO PHASEON
    
    TIMECHECK34:
    MOVF TIMERTWOFIVE, W
    SUBLW .14		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK35
    GOTO PHASEOFF
    
    TIMECHECK35:
    MOVF TIMERTWOFIVE, W
    SUBLW .15		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK36
    GOTO PHASEON
    
    TIMECHECK36:
    MOVF TIMERTWOFIVE, W
    SUBLW .16		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK37
    GOTO PHASEOFF
    
    TIMECHECK37:
    MOVF TIMERTWOFIVE, W
    SUBLW .17		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK38
    GOTO PHASEON
    
    TIMECHECK38:
    MOVF TIMERTWOFIVE, W
    SUBLW .18		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK39
    GOTO PHASEOFF
    
    TIMECHECK39:
    MOVF TIMERTWOFIVE, W
    SUBLW .19		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECK40
    GOTO PHASEON
    
    TIMECHECK40:
    MOVF TIMERTWOFIVE, W
    SUBLW .20		    ;2.5SECS
    BTFSS STATUS, Z
    GOTO TIMECHECKY1
    GOTO PHASEOFF
   ;
   ;
   ;
   ;
   ;
    TIMECHECKY1:
    MOVF PHASETIMER, W
    SUBLW .31		    ;
    BTFSS STATUS, Z
    GOTO TIMECHECKY2
    GOTO PHASE31
    
    TIMECHECKY2:
    MOVF PHASETIMER, W
    SUBLW .32		    ;
    BTFSS STATUS, Z
    GOTO TIMECHECKY3
    GOTO PHASE32
    
    TIMECHECKY3:
    MOVF PHASETIMER, W
    SUBLW .51		    ;
    BTFSS STATUS, Z
    GOTO TIMECHECKY4
    GOTO PHASE51
    
    TIMECHECKY4:
    MOVF PHASETIMER, W
    SUBLW .52		    ;
    BTFSS STATUS, Z
    GOTO TIMECHECKY11
    GOTO PHASE52
    
        
    TIMECHECKY11:
    MOVF PHASETIMER, W
    SUBLW .58		    ;
    BTFSS STATUS, Z
    GOTO TIMECHECKY12
    GOTO PHASE58
    
    TIMECHECKY12:
    MOVF PHASETIMER, W
    SUBLW .59		    ;
    BTFSS STATUS, Z
    GOTO TIMECHECKY13
    GOTO PHASE59
    
    
    TIMECHECKY13:
    MOVF PHASETIMER, W
    SUBLW .38		    ;
    BTFSS STATUS, Z
    GOTO TIMECHECKY14
    GOTO PHASE38
    
    TIMECHECKY14:
    MOVF PHASETIMER, W
    SUBLW .39		    ;
    BTFSS STATUS, Z
    GOTO TIMECHECKY15
    GOTO PHASE39
    
    TIMECHECKY15:
    MOVF PHASETIMER, W
    SUBLW .18		    ;
    BTFSS STATUS, Z
    GOTO TIMECHECKY16
    GOTO PHASE18
    
    TIMECHECKY16:
    MOVF PHASETIMER, W
    SUBLW .19		    ;
    BTFSS STATUS, Z
    GOTO CHECKT0IF
    GOTO PHASE19
    
    
   
    
    
    
    
    
    
    PHASE1:
    ;
    CLRF PORTC
    CLRF PORTD
    ;
    DMODE1:
    BTFSS CONTROL, 0
    GOTO AMODE1
    BSF PORTD, 0
    BSF PORTD, 5
    BSF PORTC, 0
    GOTO CHECKT0IF
    AMODE1:
    BTFSS CONTROL, 1
    GOTO NMODE1
    BSF PORTD, 0
    BSF PORTD, 5
    BSF PORTC, 0
    GOTO CHECKT0IF
    NMODE1:
    BTFSS CONTROL, 2
    GOTO MMODE1
    BSF PORTD, 2
    BSF PORTD, 3
    BSF PORTC, 0
    GOTO CHECKT0IF
    MMODE1:
    BTFSS CONTROL, 3
    GOTO CHECKT0IF
    BSF PORTD, 1
    BSF PORTD, 4
    BSF PORTD, 7
    BSF PORTC, 1
    GOTO CHECKT0IF
     
    
    PHASE2:
    ;
    CLRF PORTC
    CLRF PORTD
    ;
    DMODE2:
    BTFSS CONTROL, 0
    GOTO AMODE2
    BSF PORTD, 0
    BSF PORTD, 5
    BSF PORTC, 0
    GOTO CHECKT0IF
    AMODE2:
    BTFSS CONTROL, 1
    GOTO NMODE2
    BSF PORTD, 1
    BSF PORTD, 5
    BSF PORTC, 0
    GOTO CHECKT0IF
    NMODE2:
    BTFSS CONTROL, 2
    GOTO CHECKT0IF
    BSF PORTD, 2
    BSF PORTD, 3
    BSF PORTC, 0
    GOTO CHECKT0IF
    PHASE3:
    ;
    CLRF PORTC
    CLRF PORTD
    ;
    DMODE3:
    BTFSS CONTROL, 0
    GOTO AMODE3
    BSF PORTD, 0
    BSF PORTD, 5
    BSF PORTC, 0
    GOTO CHECKT0IF
    AMODE3:
    BTFSS CONTROL, 1
    GOTO NMODE3
    BSF PORTD, 2
    BSF PORTD, 3
    BSF PORTC, 0
    GOTO CHECKT0IF
    NMODE3:
    BTFSS CONTROL, 2
    GOTO CHECKT0IF
    BSF PORTD, 2
    BSF PORTD, 3
    BSF PORTC, 0
    GOTO CHECKT0IF
    PHASE4:
    ;
    CLRF PORTC
    CLRF PORTD
    ;
    DMODE4:
    BTFSS CONTROL, 0
    GOTO AMODE4
    BSF PORTD, 1
    BSF PORTD, 5
    BSF PORTC, 0
    GOTO CHECKT0IF
    AMODE4:
    BTFSS CONTROL, 1
    GOTO NMODE4
    BSF PORTD, 2
    BSF PORTD, 3
    BSF PORTC, 0
    GOTO CHECKT0IF
    NMODE4:
    BTFSS CONTROL, 2
    GOTO CHECKT0IF
    BSF PORTD, 2
    BSF PORTD, 4
    BSF PORTC, 0
    GOTO CHECKT0IF
    PHASE5:
    ;
    CLRF PORTC
    CLRF PORTD
    DMODE5:
    BTFSS CONTROL, 0
    GOTO AMODE5
    BSF PORTD, 2
    BSF PORTD, 3
    BSF PORTC, 0
    GOTO CHECKT0IF
    AMODE5:
    BTFSS CONTROL, 1
    GOTO NMODE5
    BSF PORTD, 2
    BSF PORTD, 3
    BSF PORTC, 0
    GOTO CHECKT0IF
    NMODE5:
    BTFSS CONTROL, 2
    GOTO CHECKT0IF
    BSF PORTD, 0
    BSF PORTD, 5
    BSF PORTC, 0
    GOTO CHECKT0IF
    PHASE6:
    ;
    CLRF PORTC
    CLRF PORTD
    DMODE6:
    BTFSS CONTROL, 0
    GOTO AMODE6
    BSF PORTD, 2
    BSF PORTD, 3
    BSF PORTC, 0
    GOTO CHECKT0IF
    AMODE6:
    BTFSS CONTROL, 1
    GOTO NMODE6
    BSF PORTD, 2
    BSF PORTD, 4
    BSF PORTC, 0
    GOTO CHECKT0IF
    NMODE6:
    BTFSS CONTROL, 2
    GOTO CHECKT0IF
    BSF PORTD, 0
    BSF PORTD, 5
    BSF PORTC, 0
    GOTO CHECKT0IF
    PHASE7:
    ;
    CLRF PORTC
    CLRF PORTD
    DMODE7:
    BTFSS CONTROL, 0
    GOTO AMODE7
    BSF PORTD, 2
    BSF PORTD, 3
    BSF PORTC, 0
    GOTO CHECKT0IF
    AMODE7:
    BTFSS CONTROL, 1
    GOTO NMODE7
    BSF PORTD, 2
    BSF PORTD, 5
    BSF PORTD, 6
    GOTO CHECKT0IF
    NMODE7:
    BTFSS CONTROL, 2
    GOTO CHECKT0IF
    BSF PORTD, 0
    BSF PORTD, 5
    BSF PORTC, 0
    GOTO CHECKT0IF
    PHASE8:
    ;
    CLRF PORTC
    CLRF PORTD
    DMODE8:
    BTFSS CONTROL, 0
    GOTO AMODE8
    BSF PORTD, 2
    BSF PORTD, 4
    BSF PORTC, 0
    GOTO CHECKT0IF
    AMODE8:
    BTFSS CONTROL, 1
    GOTO NMODE8
    BSF PORTD, 2
    BSF PORTD, 5
    BSF PORTD, 6
    GOTO CHECKT0IF
    NMODE8:
    BTFSS CONTROL, 2
    GOTO CHECKT0IF
    BSF PORTD, 1
    BSF PORTD, 5
    BSF PORTC, 0
    GOTO CHECKT0IF
    PHASE9:
    ;
    CLRF PORTC
    CLRF PORTD
    DMODE9:
    BTFSS CONTROL, 0
    GOTO AMODE9
    BSF PORTD, 2
    BSF PORTD, 5
    BSF PORTD, 6
    GOTO CHECKT0IF
    AMODE9:
    BTFSS CONTROL, 1
    GOTO NMODE9
    BSF PORTD, 2
    BSF PORTD, 5
    BSF PORTD, 6
    GOTO CHECKT0IF
    NMODE9:
    BTFSS CONTROL, 2
    GOTO CHECKT0IF
    BSF PORTD, 2
    BSF PORTD, 5
    BSF PORTD, 6
    GOTO CHECKT0IF
    PHASE10:
    ;
    CLRF PORTC
    CLRF PORTD
    DMODE10:
    BTFSS CONTROL, 0
    GOTO AMODE10
    BSF PORTD, 2
    BSF PORTD, 5
    BSF PORTD, 7
    GOTO CHECKT0IF
    AMODE10:
    BTFSS CONTROL, 1
    GOTO NMODE10
    BSF PORTD, 2
    BSF PORTD, 5
    BSF PORTD, 7
    GOTO CHECKT0IF
    NMODE10:
    BTFSS CONTROL, 2
    GOTO CHECKT0IF
    BSF PORTD, 2
    BSF PORTD, 5
    BSF PORTD, 7
    GOTO CHECKT0IF
    PHASE11:
    ;
    CLRF PORTC
    CLRF PORTD
    CLRF PHASETIMER
    GOTO MAINLOOP
    
    PHASEON:
    BSF PORTC, 1

    BTFSS CONTROL, 3
    GOTO CHECKT0IF
    CLRF PORTC
    CLRF PORTD
    BSF PORTD, 1
    BSF PORTD, 4
    BSF PORTD, 7
    BSF PORTC, 1
    GOTO CHECKT0IF
    PHASEOFF:
    BCF PORTC, 1
    BTFSS CONTROL, 3
    GOTO CHECKT0IF
    CLRF PORTC
    CLRF PORTD
    GOTO CHECKT0IF

    
    
    PHASE18:
    ;
    BTFSS CONTROL, 1
    GOTO CHECKT0IF
    BCF PORTD, 1
    GOTO CHECKT0IF
    
    
    PHASE19:
    ;
    BTFSS CONTROL, 1
    GOTO CHECKT0IF
    BSF PORTD, 1
    GOTO CHECKT0IF
    
    
    
    PHASE31:
    ;
    BTFSS CONTROL, 0
    GOTO NMODE31
    BCF PORTD, 1
    GOTO CHECKT0IF
    
    NMODE31:
    BTFSS CONTROL, 2
    GOTO CHECKT0IF
    BCF PORTD, 4
    GOTO CHECKT0IF
    
    PHASE32:
    ;
    BTFSS CONTROL, 0
    GOTO NMODE32
    BSF PORTD, 1
    GOTO CHECKT0IF
    
    NMODE32:
    BTFSS CONTROL, 2
    GOTO CHECKT0IF
    BSF PORTD, 4
    GOTO CHECKT0IF
    
    
    PHASE38:
    ;
    BTFSS CONTROL, 1
    GOTO CHECKT0IF
    BCF PORTD, 4
    GOTO CHECKT0IF
    
    
    PHASE39:
    ;
    BTFSS CONTROL, 1
    GOTO CHECKT0IF
    BSF PORTD, 4
    GOTO CHECKT0IF
    
    
    
    PHASE51:
    ;
    BTFSS CONTROL, 0
    GOTO NMODE51
    BCF PORTD, 4
    GOTO CHECKT0IF
    
    NMODE51:
    BTFSS CONTROL, 2
    GOTO CHECKT0IF
    BCF PORTD, 1
    GOTO CHECKT0IF
    
    PHASE52:
    ;
    BTFSS CONTROL, 0
    GOTO NMODE52
    BSF PORTD, 4
    GOTO CHECKT0IF
    
    NMODE52:
    BTFSS CONTROL, 2
    GOTO CHECKT0IF
    BSF PORTD, 1
    GOTO CHECKT0IF
    
    
    PHASE58:
    ;
    BTFSS CONTROL, 0
    GOTO AMODE58
    BCF PORTD, 7
    GOTO CHECKT0IF
    AMODE58:
    BTFSS CONTROL, 1
    GOTO NMODE58
    BCF PORTD, 7
    GOTO CHECKT0IF
    NMODE58:
    BTFSS CONTROL, 2
    GOTO CHECKT0IF
    BCF PORTD, 7
    GOTO CHECKT0IF
    
    PHASE59:
    ;
    BTFSS CONTROL, 0
    GOTO AMODE59
    BSF PORTD, 7
    GOTO CHECKT0IF
    AMODE59:
    BTFSS CONTROL, 1
    GOTO NMODE59
    BSF PORTD, 7
    GOTO CHECKT0IF
    NMODE59:
    BTFSS CONTROL, 2
    GOTO CHECKT0IF
    BSF PORTD, 7
    GOTO CHECKT0IF
    
    
    
    
    
    
    
    
    

;SUBR
INITTMR0
    BSF STATUS, RP0		;
    BCF STATUS, RP1		;BANK 1
    BCF OPTION_REG, T0CS	;TEMP ON
    BCF OPTION_REG, PSA 	;
    BSF OPTION_REG, PS2		;
    BSF OPTION_REG, PS1		;
    BCF OPTION_REG, PS0 	; PRESCALER 1:128
    BCF STATUS, RP0		;
    BCF STATUS, RP1		;BANK 0
    MOVLW .61			;
    MOVWF TMR0 			;MOVE W TO TMR0
RETURN

DELAY
    MOVLW .150
    MOVWF D2
RES1:
    MOVLW .100
    MOVWF D1
RES2:    
    DECFSZ D1, F
    GOTO RES2
    DECFSZ D2, F
    GOTO RES1
RETURN
    
END